// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace stockymodels.Migrations
{
    [Migration("20260312000000_002CreateProjections")]
    partial class _002CreateProjections
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
